services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_net
    # ports:
    #   - "3000:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - app_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/static:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - app

networks:
  app_net:
    driver: bridge